/**
 * Server-side import of expanded product data
 */

// Define the mock products structure for server use
interface MockProduct {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  rating: number;
  category: string;
  brand: string;
  inStock: boolean;
  discount: number;
  tags: string[];
  reviews: number;
  priceRange: string;
  colors?: string[];
  specs?: Record<string, any>;
}

// Sample of the first 20 products from the client-side mock data
// These are used as a fallback for the server API
export default [
  {
    "id": "1",
    "name": "Ultra Wireless Headphones",
    "description": "Premium noise-cancelling wireless headphones with 40-hour battery life.",
    "price": 299.99,
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format",
    "rating": 4.7,
    "category": "electronics",
    "brand": "SoundMax",
    "inStock": true,
    "discount": 15,
    "tags": ["wireless", "audio", "premium"],
    "reviews": 128,
    "priceRange": "200-500"
  },
  {
    "id": "2",
    "name": "Premium Running Shoes",
    "description": "Lightweight and responsive running shoes with advanced cushioning technology.",
    "price": 149.95,
    "image": "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=500&auto=format",
    "rating": 4.5,
    "category": "clothing",
    "brand": "SpeedStep",
    "inStock": true,
    "discount": 0,
    "tags": ["running", "sports", "footwear"],
    "reviews": 94,
    "priceRange": "100-200"
  },
  {
    "id": "3",
    "name": "Smart Watch Pro",
    "description": "Advanced fitness tracking with heart rate monitor and GPS.",
    "price": 349.99,
    "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format",
    "rating": 4.8,
    "category": "electronics",
    "brand": "TechFit",
    "inStock": true,
    "discount": 10,
    "tags": ["smartwatch", "fitness", "wearable"],
    "reviews": 215,
    "priceRange": "200-500"
  },
  {
    "id": "4",
    "name": "Designer Sunglasses",
    "description": "UV-protected, polarized lenses in a classic style.",
    "price": 189.99,
    "image": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&auto=format",
    "rating": 4.3,
    "category": "accessories",
    "brand": "VueChic",
    "inStock": false,
    "discount": 5,
    "tags": ["sunglasses", "fashion", "summer"],
    "reviews": 63,
    "priceRange": "100-200"
  },
  {
    "id": "5",
    "name": "Wireless Earbuds",
    "description": "True wireless earbuds with active noise cancellation and waterproof design.",
    "price": 159.95,
    "image": "https://images.unsplash.com/photo-1594482628048-848677f1a471?w=500&auto=format",
    "rating": 4.6,
    "category": "electronics",
    "brand": "SoundMax",
    "inStock": true,
    "discount": 0,
    "tags": ["earbuds", "wireless", "audio"],
    "reviews": 102,
    "priceRange": "100-200"
  },
  {
    "id": "6",
    "name": "Ultrabook Laptop 15\"",
    "description": "Ultra-thin and lightweight laptop with 12-hour battery life.",
    "price": 1299.99,
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&auto=format",
    "rating": 4.9,
    "category": "electronics",
    "brand": "TechBook",
    "inStock": true,
    "discount": 0,
    "tags": ["laptop", "computer", "ultrabook"],
    "reviews": 87,
    "priceRange": "1000+"
  },
  {
    "id": "7",
    "name": "Mechanical Keyboard",
    "description": "RGB backlit mechanical keyboard with customizable switches.",
    "price": 129.95,
    "image": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500&auto=format",
    "rating": 4.4,
    "category": "electronics",
    "brand": "TypeMaster",
    "inStock": true,
    "discount": 0,
    "tags": ["keyboard", "gaming", "mechanical"],
    "reviews": 56,
    "priceRange": "100-200"
  },
  {
    "id": "8",
    "name": "Noise-Cancelling Headset",
    "description": "Professional-grade headset with crystal clear microphone.",
    "price": 249.99,
    "image": "https://images.unsplash.com/photo-1563473213013-de2a0133c100?w=500&auto=format",
    "rating": 4.7,
    "category": "electronics",
    "brand": "ClearSound",
    "inStock": true,
    "discount": 0,
    "tags": ["headset", "audio", "professional"],
    "reviews": 43,
    "priceRange": "200-500"
  },
  {
    "id": "9",
    "name": "Performance Athletic Shoes",
    "description": "High-performance athletic shoes with responsive cushioning.",
    "price": 179.95,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format",
    "rating": 4.6,
    "category": "clothing",
    "brand": "AthleticEdge",
    "inStock": true,
    "discount": 20,
    "tags": ["shoes", "athletic", "sports"],
    "reviews": 77,
    "priceRange": "100-200"
  },
  {
    "id": "10",
    "name": "Ergonomic Office Chair",
    "description": "Fully adjustable ergonomic chair with lumbar support.",
    "price": 399.99,
    "image": "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=500&auto=format",
    "rating": 4.8,
    "category": "home",
    "brand": "ComfortPlus",
    "inStock": true,
    "discount": 10,
    "tags": ["chair", "office", "ergonomic"],
    "reviews": 64,
    "priceRange": "200-500"
  },
  {
    "id": "11",
    "name": "4K Ultra HD Monitor",
    "description": "32-inch 4K monitor with HDR support and eye-care technology.",
    "price": 449.99,
    "image": "https://images.unsplash.com/photo-1607016284318-d1384f79bed8?w=500&auto=format",
    "rating": 4.7,
    "category": "electronics",
    "brand": "VisualPro",
    "inStock": true,
    "discount": 5,
    "tags": ["monitor", "4k", "computer"],
    "reviews": 38,
    "priceRange": "200-500"
  },
  {
    "id": "12",
    "name": "Smartphone Pro Max",
    "description": "Latest flagship smartphone with advanced camera system and all-day battery.",
    "price": 1099.99,
    "image": "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=500&auto=format",
    "rating": 4.9,
    "category": "electronics",
    "brand": "TechGiant",
    "inStock": true,
    "discount": 0,
    "tags": ["smartphone", "mobile", "camera"],
    "reviews": 156,
    "priceRange": "1000+"
  },
  {
    "id": "13",
    "name": "Wireless Gaming Mouse",
    "description": "Ultra-responsive wireless gaming mouse with customizable buttons.",
    "price": 89.99,
    "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format",
    "rating": 4.5,
    "category": "electronics",
    "brand": "GameTech",
    "inStock": true,
    "discount": 0,
    "tags": ["mouse", "gaming", "wireless"],
    "reviews": 92,
    "priceRange": "50-100"
  },
  {
    "id": "14",
    "name": "Smart Home Speaker",
    "description": "Voice-controlled smart speaker with premium sound quality.",
    "price": 199.99,
    "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500&auto=format",
    "rating": 4.6,
    "category": "electronics",
    "brand": "HomeSmart",
    "inStock": true,
    "discount": 15,
    "tags": ["speaker", "smart home", "voice control"],
    "reviews": 81,
    "priceRange": "100-200"
  },
  {
    "id": "15",
    "name": "Digital Drawing Tablet",
    "description": "Professional drawing tablet with pressure sensitivity and wireless connectivity.",
    "price": 349.99,
    "image": "https://images.unsplash.com/photo-1561886318-ac45ec4f0585?w=500&auto=format",
    "rating": 4.7,
    "category": "electronics",
    "brand": "ArtPro",
    "inStock": true,
    "discount": 0,
    "tags": ["tablet", "drawing", "digital art"],
    "reviews": 47,
    "priceRange": "200-500"
  },
  {
    "id": "16",
    "name": "Portable Bluetooth Speaker",
    "description": "Waterproof, durable Bluetooth speaker with 24-hour battery life.",
    "price": 129.99,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format",
    "rating": 4.4,
    "category": "electronics",
    "brand": "SoundMax",
    "inStock": true,
    "discount": 10,
    "tags": ["speaker", "bluetooth", "portable"],
    "reviews": 118,
    "priceRange": "100-200"
  },
  {
    "id": "17",
    "name": "Professional Hair Dryer",
    "description": "Salon-quality hair dryer with ionic technology and multiple heat settings.",
    "price": 149.99,
    "image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=500&auto=format",
    "rating": 4.3,
    "category": "beauty",
    "brand": "StylePro",
    "inStock": true,
    "discount": 0,
    "tags": ["hair dryer", "beauty", "styling"],
    "reviews": 73,
    "priceRange": "100-200"
  },
  {
    "id": "18",
    "name": "Multi-Function Blender",
    "description": "High-powered blender with multiple attachments for various food preparation tasks.",
    "price": 199.95,
    "image": "https://images.unsplash.com/photo-1622480916113-9000ac49b79d?w=500&auto=format",
    "rating": 4.6,
    "category": "home",
    "brand": "KitchenPro",
    "inStock": true,
    "discount": 5,
    "tags": ["blender", "kitchen", "appliance"],
    "reviews": 65,
    "priceRange": "100-200"
  },
  {
    "id": "19",
    "name": "Robot Vacuum Cleaner",
    "description": "Smart robot vacuum with mapping technology and automated cleaning schedules.",
    "price": 399.99,
    "image": "https://images.unsplash.com/photo-1573398501899-c7cbc6b82f61?w=500&auto=format",
    "rating": 4.7,
    "category": "home",
    "brand": "CleanTech",
    "inStock": true,
    "discount": 15,
    "tags": ["vacuum", "robot", "smart home"],
    "reviews": 89,
    "priceRange": "200-500"
  },
  {
    "id": "20",
    "name": "Premium Coffee Maker",
    "description": "Programmable coffee maker with built-in grinder and temperature control.",
    "price": 249.99,
    "image": "https://images.unsplash.com/photo-1570701123784-6b32e5506190?w=500&auto=format",
    "rating": 4.8,
    "category": "home",
    "brand": "BrewMaster",
    "inStock": true,
    "discount": 0,
    "tags": ["coffee maker", "kitchen", "appliance"],
    "reviews": 103,
    "priceRange": "200-500"
  },
  // Extended products for IDs > 20
  {
    "id": "21",
    "name": "Sony Alpha Pro Mirrorless Camera",
    "description": "Experience cutting-edge technology with the Sony Alpha Pro Mirrorless Camera. Featuring High-Resolution Display, Water Resistant Design, and Crystal Clear Audio, this device delivers exceptional performance for all your needs.",
    "price": 875.26,
    "image": "https://source.unsplash.com/random/600x400?cameras&sig=21SonyAlpha",
    "rating": 4.2,
    "category": "electronics",
    "brand": "Sony",
    "inStock": true,
    "discount": 20,
    "tags": ["electronics", "cameras", "sony", "premium"],
    "reviews": 158,
    "priceRange": "500+"
  },
  {
    "id": "22",
    "name": "Adidas Performance Training Tee",
    "description": "Discover exceptional comfort with our bestselling Adidas Performance Training Tee. Crafted from premium Recycled Polyester with Moisture-Wicking Fabric.",
    "price": 86.56,
    "image": "https://source.unsplash.com/random/600x400?activewear&sig=22AdidasPerformance",
    "rating": 4.7,
    "category": "clothing",
    "brand": "Adidas",
    "inStock": true,
    "discount": 0,
    "tags": ["clothing", "activewear", "adidas", "trending"],
    "reviews": 175,
    "priceRange": "50-100"
  },
  {
    "id": "30",
    "name": "Bose Ultra Nova Headset",
    "description": "Meet the revolutionary Bose Ultra Nova Headset, designed for the modern Professionals. With Noise Cancellation, Wireless Connectivity, and up to 20 hours of battery life.",
    "price": 299.99,
    "image": "https://source.unsplash.com/random/600x400?headphones&sig=30Bose",
    "rating": 4.7,
    "category": "electronics",
    "brand": "Bose",
    "inStock": true,
    "discount": 10,
    "tags": ["electronics", "headphones", "bose", "premium"],
    "reviews": 214,
    "priceRange": "200-500"
  },
  {
    "id": "45",
    "name": "Nintendo Switch OLED Model",
    "description": "Experience cutting-edge technology with the Nintendo Switch OLED Model. Featuring High-Resolution Display, Energy Efficient Performance, and Wireless Connectivity.",
    "price": 349.99,
    "image": "https://source.unsplash.com/random/600x400?nintendo&sig=45Nintendo",
    "rating": 4.9,
    "category": "electronics",
    "brand": "Nintendo",
    "inStock": true,
    "discount": 0,
    "tags": ["electronics", "games", "nintendo", "bestseller"],
    "reviews": 284,
    "priceRange": "200-500"
  },
  {
    "id": "50",
    "name": "Fisher-Price Interactive Globe",
    "description": "Spark imagination and learning with the engaging Fisher-Price Interactive Globe. Designed to develop Spatial Awareness and Critical Thinking.",
    "price": 59.99,
    "image": "https://source.unsplash.com/random/600x400?educational&sig=50Fisher-Price",
    "rating": 4.8,
    "category": "toys",
    "brand": "Fisher-Price",
    "inStock": true,
    "discount": 10,
    "tags": ["toys", "educational", "fisher-price", "trending"],
    "reviews": 94,
    "priceRange": "50-100"
  },
  {
    "id": "75",
    "name": "Microsoft Surface Pro Tablet",
    "description": "Upgrade your tech collection with the premium Microsoft Surface Pro Tablet. Built with High-Resolution Display and equipped with Extended Battery Life.",
    "price": 899.99,
    "image": "https://source.unsplash.com/random/600x400?tablet&sig=75Microsoft",
    "rating": 4.8,
    "category": "electronics",
    "brand": "Microsoft",
    "inStock": true,
    "discount": 5,
    "tags": ["electronics", "tablets", "microsoft", "premium"],
    "reviews": 127,
    "priceRange": "500+"
  },
  {
    "id": "92",
    "name": "Apple Omega Smart Watch",
    "description": "Experience cutting-edge technology with the Apple Omega Smart Watch. Featuring Advanced AI Capabilities, Wireless Connectivity, and Extended Battery Life.",
    "price": 499.99,
    "image": "https://source.unsplash.com/random/600x400?smartwatch&sig=92Apple",
    "rating": 4.9,
    "category": "electronics",
    "brand": "Apple",
    "inStock": true,
    "discount": 0,
    "tags": ["electronics", "wearables", "apple", "premium"],
    "reviews": 312,
    "priceRange": "200-500"
  },
  {
    "id": "100",
    "name": "Ninja Multi-Functional Use Blender",
    "description": "Transform your space with the elegant Ninja Multi-Functional Use Blender. Featuring Programmable Timer and Easy Assembly.",
    "price": 129.99,
    "image": "https://source.unsplash.com/random/600x400?blender&sig=100Ninja",
    "rating": 4.7,
    "category": "home",
    "brand": "Ninja",
    "inStock": true,
    "discount": 10,
    "tags": ["home", "kitchen", "ninja", "bestseller"],
    "reviews": 246,
    "priceRange": "100-200"
  },
  {
    "id": "118",
    "name": "Samsung Galaxy Book Pro",
    "description": "Ultra-thin and powerful laptop with AMOLED display and all-day battery life. Perfect for professionals on the go.",
    "price": 1299.99,
    "image": "https://source.unsplash.com/random/600x400?laptop&sig=118Samsung",
    "rating": 4.8,
    "category": "electronics",
    "brand": "Samsung",
    "inStock": true,
    "discount": 5,
    "tags": ["electronics", "laptops", "samsung", "premium"],
    "reviews": 83,
    "priceRange": "1000+"
  },
  {
    "id": "125",
    "name": "Sony WH-1000XM5 Headphones",
    "description": "Industry-leading noise cancellation with exceptional sound quality and comfort for long listening sessions.",
    "price": 349.99,
    "image": "https://source.unsplash.com/random/600x400?headphones&sig=125Sony",
    "rating": 4.9,
    "category": "electronics",
    "brand": "Sony",
    "inStock": true,
    "discount": 0,
    "tags": ["electronics", "headphones", "sony", "premium"],
    "reviews": 178,
    "priceRange": "200-500"
  },
  {
    "id": "130",
    "name": "Dyson V12 Vacuum",
    "description": "Powerful cordless vacuum with advanced filtration and intelligent sensors for all floor types.",
    "price": 599.99,
    "image": "https://source.unsplash.com/random/600x400?vacuum&sig=130Dyson",
    "rating": 4.7,
    "category": "home",
    "brand": "Dyson",
    "inStock": true,
    "discount": 10,
    "tags": ["home", "appliances", "dyson", "premium"],
    "reviews": 142,
    "priceRange": "500+"
  }
] as MockProduct[];